import os
import io
import base64
import json
from google import genai
from pydantic import BaseModel
from typing import List

class ReceiptItem(BaseModel):
    item_name: str
    quantity: str
    price: float

class ReceiptExtraction(BaseModel):
    customer_name: str
    items: List[ReceiptItem]
    total_amount: float

class SahayakVision:
    def __init__(self):
        self.client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

    def process_receipt(self, base64_image: str) -> dict:
        """
        Processes a base64 image string of a handwritten receipt using Gemini 1.5 Flash.
        Returns the extracted Customer Name, Items, and Total Amount.
        """
        # Remove data URI prefix if present
        if "," in base64_image:
            base64_image = base64_image.split(",")[1]
            
        image_bytes = base64.b64decode(base64_image)
        
        prompt = """
        Analyze this handwritten receipt generated by a kirana store in India.
        Extract the following strictly from the image:
        1. Customer Name (if not found, output "Unknown")
        2. Items purchased (name, quantity, and approximate price if available)
        3. Total Amount (must be a float value, drop the currency symbols)
        
        Return the information STRICTLY matching the provided JSON schema.
        """
        
        response = self.client.models.generate_content(
            model='gemini-1.5-flash',
            contents=[
                prompt,
                genai.types.Part.from_bytes(
                    data=image_bytes,
                    mime_type='image/png',
                )
            ],
            config=genai.types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=ReceiptExtraction,
            )
        )
        
        return json.loads(response.text)
